# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: smart
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  config:
    import: classpath:info.yml
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${oracle.url}
    username: ${oracle.username}
    password: ${oracle.password}
  mail:
    host: smtp.naver.com
    username: ${naver.email.username}
    password: ${naver.email.password}
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${naver.client-id}
            client-secret: ${naver.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: ${baseURL}/login/oauth2/code/naver
          kakao:
            client-id: ${kakao.client-id}
            authorization-grant-type: authorization_code
            redirect-uri: ${baseURL}/login/oauth2/code/kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port: 8080
  servlet:
    context-path: /smart
mybatis:
  mapper-locations: classpath:sqlmap/*Mapper.xml
  config-location: classpath:sqlmap/typeConfig.xml
